version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"    # Jenkins UI
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/.aws:/root/.aws:ro
      - /home/ec2-user/.kube:/root/.kube:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_data: